//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public string AppointmentID { get; set; }
        public System.DateTime BookingDateAndTime { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string AppointmentTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
