//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public string CaseID { get; set; }
        public string EmployeeID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime ConsultationDate { get; set; }
        public string Observations { get; set; }
        public string Investigations { get; set; }
        public string Diagnosis { get; set; }
        public string Prescription { get; set; }
        public string HasMC { get; set; }
        public int NumberOfDaysOfMC { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
