//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Leave = new HashSet<Leave>();
        }
    
        public string EmployeeID { get; set; }
        public string Password { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public double Salary { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string NOKRelationship { get; set; }
        public string NOKName { get; set; }
        public string NOKPhoneNumber { get; set; }
        public System.DateTime DateJoin { get; set; }
        public double AllocatedAnnualLeave { get; set; }
        public double AllocatedMedicalLeave { get; set; }
        public double AllocatedHospitalizationLeave { get; set; }
        public double AllocatedPaternalOrMaternalLeave { get; set; }
        public double AllocatedCompassionateLeave { get; set; }
        public double AllocatedChildcareLeave { get; set; }
        public string Superior { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leave { get; set; }
    }
}
