//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public string ItemID { get; set; }
        public double QuantityOrdered { get; set; }
        public string UnitOfMeasure { get; set; }
        public double OrderPrice { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public System.DateTime DateExpected { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string SupplierID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
