//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sourcing
    {
        public string SourceID { get; set; }
        public System.DateTime DateSourced { get; set; }
        public double CostPrice { get; set; }
        public System.DateTime DateValidUntil { get; set; }
        public double MinOrderQuantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public string LeadTime { get; set; }
        public string Status { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
